[package]
name = "day-04"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.2"

[dev-dependencies]
divan = { workspace = true }

[[bench]]
name = "day-04"
path = "benches/benchmarks.rs"
harness = false
