[package]
name = "day-03"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
divan = { workspace = true }

[[bench]]
name = "day-03"
path = "benches/benchmarks.rs"
harness = false

[dependencies]
regex = "1.10.2"
