[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
divan = { workspace = true }

[[bench]]
name = "{{project-name}}"
path = "benches/benchmarks.rs"
harness = false
