[package]
name = "day-01"
version = "0.1.0"
edition = "2021"

[dependencies]
fancy-regex = { workspace = true }
rstest = { workspace = true }

[dev-dependencies]
divan = { workspace = true }

[[bench]]
name = "day-01"
path = "benches/benchmarks.rs"
harness = false
